version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          VERSION_TAG=`cat VERSION`
          GIT_TAG=`git log -1 --pretty=%h`
          docker build -t ironarachne/datacore:$VERSION_TAG -t ironarachne/datacore:$GIT_TAG -t ironarachne/datacore:latest .
  publish:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          VERSION_TAG=`cat VERSION`
          GIT_TAG=`git log -1 --pretty=%h`
          docker build -t ironarachne/datacore:$VERSION_TAG -t ironarachne/datacore:$GIT_TAG -t ironarachne/datacore:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ironarachne/datacore:$VERSION_TAG
          docker push ironarachne/datacore:$GIT_TAG
          docker push ironarachne/datacore:latest
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build
      - publish:
          filters:
            branches:
              only: release
